
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://localhost:5001/api
        - NODE_ENV=production
    ports:
      - "8080:8080"

  # Flask API service
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/emptycup
      - PORT=5001
    depends_on:
      db:
        condition: service_healthy
    command: python app.py

  # Database service
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=emptycup
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d emptycup"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
