[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_ENVIRONMENT = "production"
  VITE_API_BASE_URL = "https://designer-shortlist-platform-production.up.railway.app/api"

[context.deploy-preview.environment]
  VITE_ENVIRONMENT = "preview"

[context.branch-deploy.environment]
  VITE_ENVIRONMENT = "development"
