[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_ENVIRONMENT = "production"
  # VITE_API_BASE_URL will be set in Netlify dashboard

[context.deploy-preview.environment]
  VITE_ENVIRONMENT = "preview"

[context.branch-deploy.environment]
  VITE_ENVIRONMENT = "development"
